### ISSUE TITLE
DittoSwiftTools Blog post + README

### ISSUE THREAD

**Issue by okdistribute** [getditto/DittoSwiftTools#10]
Should clean up the README to describe how to use this and what it contains that is at par with other swift packages.

For example: https://github.com/YannickL/QRCodeReader.swift

Then we should write a blog post and post this out on the socials.

**Comment by okdistribute** [comment]
@texasRanger09 @magicwave which one of you wants to take this on? This should happen sometime after the retreat.

**Comment by rratner** [comment]
Hey guys, no rush on this, but whoever takes this on should be sure to reach out to me as well for when we are ready to plan out the blog post.

**Comment by texasRanger09** [comment]
I can do it. @rratner let's connect after the meetup to go over the blog

**Comment by okdistribute** [comment]
The disk usage should be done, yeah. Once before is out, we should update the status of tools to v4 and then incorporate the disk usage.
