### ISSUE TITLE
Swift - Crash (assertion) occurring when Exporting Logs

### ISSUE THREAD

**Issue by radazzouz** [getditto/DittoSwiftTools#104]
## How to Reproduce:

- Launch DittoToolsApp from `main` on a device or simulator
- Tap on Logging > Export Log
- Tap on the alerts "Export" button
 
https://github.com/getditto/DittoSwiftTools/assets/7443038/fb7d7dfe-a7b0-4f9f-a46d-0d5a4dca4dad

## Expected:

The logs should be exported.

## Actual:

💥 An assertion occurs in https://github.com/getditto/DittoSwiftTools/blob/f4667050e0ca87133b2ab8612a68f996af46bc6b/Sources/DittoExportLogs/DittoLogManager.swift#L48

<img width="1582" alt="Screenshot 2024-04-25 at 2 57 29 PM" src="https://github.com/getditto/DittoSwiftTools/assets/7443038/9572174c-bcae-4ae2-9591-b4afbac732a9">

**Comment by radazzouz** [comment]
We can use the upcoming API in 4.8.0 to simplify exporting logs. See https://github.com/getditto/ditto/pull/12691

**Comment by konstantinbe** [comment]
#12691 should fix this.

**Comment by bplattenburg** [comment]
Closing based on the above comment and the fact that we will migrate this tool to use the new accessor for the internal rotating log files as part of https://github.com/getditto/DittoSwiftTools/issues/99.

Please re-open if those two don't resolve this issue.
