### ISSUE TITLE
Reduce DittoSwiftTools iOS target version from 15.0 to 14.0

### ISSUE THREAD

**Issue by magicwave** [getditto/DittoSwiftTools#109]
I believe I upgraded the target for an API in the Ditto Peers module, but I think it would be possible to find an iOS 14 API for the task.

**Comment by bplattenburg** [comment]
This is in a surprisingly awkward place today - the package technically supports iOS 14, but many tools have code gated by `@available(iOS 15, *)`.

- AllToolsMenu
- DittoDataBrowser
- DittoExportLogs
- DittoHeartbeat
- DittoPeersList

We really need to clean those up to make sure these tools are available and usable by customers on iOS 14.
