### ISSUE TITLE
Version 4.6 introduces breaking change

### ISSUE THREAD

**Issue by magicwave** [getditto/DittoSwiftTools#133]
The 4.6.0 release tag commit comment says, "This release is compatible with DittoSwift version 4.0.0 and above.", however the `DittoLogManager` `static var logFileURL: URL!` API in the `DittoExportLogs` module was removed in that release. 

This breaks code that worked on previous versions of 4.x that depended on that property. For example, this code:  
`let logFileURL = DittoLogManager.shared.logFileURL`  
now produces a compiler error:  
```Value of type 'DittoLogManager' has no member 'logFileURL'```

**Comment by bplattenburg** [comment]
@magicwave What action can we take to resolve this? Is updating the release notes for affected versions enough?

**Comment by bplattenburg** [comment]
It turns out this is still broken in 6.0.0, Will get it fixes ASAP.

**Comment by bplattenburg** [comment]
It looks like this was broken as part of https://github.com/getditto/DittoSwiftTools/pull/72. I don't know enough of the history there to know why this was removed and what the implications of adding it back are. @texasRanger09, do you remember from January?

**Comment by bplattenburg** [comment]
Although, as I reconsider, maybe fixing it isn't the right answer, it's valid to have breaking changes at this point since we've gone through 2 major versions since this was introduced. What I don't know is the original intent of exposing that and what a migration path looks like for callers. Maybe its totally fine to break this 🤔

**Comment by bplattenburg** [comment]
I've updated the 4.6.0 release notes to indicate the unintentional breaking change and linked back to here.
