### ISSUE TITLE
Compilation fails with error: 'No such module DittoDataBrowser'

### ISSUE THREAD

**Issue by magicwave** [getditto/DittoSwiftTools#14]
The compiler error appears in Pages/DataBrowser.swift at the `import DittoDataBrowser` statement.

**Comment by magicwave** [comment]
UPDATE: this appears to be fixed in the [Update to v3](https://github.com/getditto/DittoSwiftTools/pull/13) PR (not yet merged) which sets the package to DittoBrowser branch.

**Comment by okdistribute** [comment]
This should be fixed now
