### ISSUE TITLE
Refactor ExportLogs target for UIKit and SwiftUI

### ISSUE THREAD

**Issue by texasRanger09** [getditto/DittoSwiftTools#20]
Current implementation works fine with SwiftUI, but needs to be refactored to work with SwiftUI and UIKit.

**Comment by okdistribute** [comment]
Do we need to support UIKit?

**Comment by texasRanger09** [comment]
Mostly depends on if there is a customer who uses UIKit and wants this package. If not, then we can leave it out right now and I can just manually add the export logs feature to our current demo apps that use UiKit, like Inventory.

**Comment by okdistribute** [comment]
I’d probably just ship the Swift version first and leave the UIKit improvements as a feature request for later.
