### ISSUE TITLE
Issue commands to a mesh of devices 

### ISSUE THREAD

**Issue by okdistribute** [getditto/DittoSwiftTools#23]
Tell all devices to remove everything from their local store.

## Problem

This is actually an interesting case that will come up a lot on prototyping because developers want to issue a command across the network to reset data directory. The developers call it a “nuke everything button.”  It is not entirely clear for someone new to peer-to-peer how this would get done!

## Hack

The solution we worked on in the meantime, without code changes, was to disconnect all devices from each other using Bluetooth and click remove all on each one, and then turn Bluetooth back on, and that solved it. We weren’t sure where the fake documents came from because they had several apps involved. 
This is because their remove all button didn’t subscribe to find all before performing the remove

## Solution

One way this can be accomplished is through a [Command Pattern](https://www.tutorialspoint.com/design_pattern/command_pattern.htm#).

Commands can be issued as documents. Each command should have an expiration date. When a device receives a command, it should issue it.

Start with one command - removeAll. This command could take argument such as collection names to remove. However, it's also fair for a first version to iterate through all local collections and remove everything.

Make sure that when a command has been processed, it is only processed precisely once per device. This can be done by keeping expiration dates relatively short (eg, 5 seconds). The expiration date should be only as long as you're expecting all of the devices in the mesh to receive the command and process it.

If you can't rely on the clocks, then you can keep a local list of commands that you've already issued, to make sure that you only issue the same command once. Then the expiration date can be longer.

## Tool

- [ ] A button that subscribes to all data in the mesh and deletes it locally.

**Comment by kndoshn** [comment]
I'm interested how we han accomplish this feature.
Should `remove()` wait for enough amount of time? check the doc and make sure your local data isn't too old?

```swift
func removeAll() {
    let query = ditto.store.collection("items").findAll()

    subscription = query.subscribe()


    // Wait for a while before remove? 10 seconds enough??
    DispatchQueue.main.asyncAfter(deadline: .now() + 10) {
        query.remove()
    }


    // Check time to make sure your data is latest?
    liveQuery = query.observeLocal { docs, event in
        switch event {
        case .update(_):

            let date = docs.first?["updatedDate"]
            // check time?

        }
    }
}
```

**Comment by okdistribute** [comment]
One way that we can this is by using a [Command Pattern](https://www.tutorialspoint.com/design_pattern/command_pattern.htm#).

Commands can be issued as documents. Each command should have an expiration date. When a device receives a command, it should issue it.

Start with one command - removeAll. This command could take argument such as collection names, but it's also fair for a first version to be basic and remove everything locally.

Make sure that when a command has been processed, it is only processed precisely once per device. This can be done by keeping expiration dates short. It can also be done by giving each Command a unique _id, and persisting a local store of issued commands.

**Comment by okdistribute** [comment]
This will be tackled in https://github.com/getditto/POSHealth/issues/9
