### ISSUE TITLE
Publish to App Store

### ISSUE THREAD

**Issue by okdistribute** [getditto/DittoSwiftTools#33]
- [ ] Remove PresenceViewer App from the Store
- [ ] Add the tools standalone app instead.

**Comment by bplattenburg** [comment]
@texasRanger09 based on our conversation around current usage, this may not be valuable to publish to the store as its not really used externally today (and can still be built & run locally if needed), and would add on to the number of apps we're managing and publishing today.

@okdistribute any objections to closing this and not publishing this after all? I don't think we publish this for Android either.

**Comment by okdistribute** [comment]
Yeah this makes sense to me
