### ISSUE TITLE
SPM fails to install release 3.0.6 in Xcode 14

### ISSUE THREAD

**Issue by magicwave** [getditto/DittoSwiftTools#52]
STR:
1. In a new Xcode project, add `DittoSwiftPackage`; set Dependency Rule to  `4.0.0 - Next Major`
2. add `DittoSwiftTools`; set Dependency Rule to `3.0.6 - Next Major`

OBS:
SPM fails to resolve

EXP:
SPM installs DittoSwiftTools v3.0.6 for Dependency Rule `3.0.6 - Next Major`

<img width="1084" alt="DittoSwiftTools_SPM-fail" src="https://github.com/getditto/DittoSwiftTools/assets/10930016/69cc9d21-1cf0-45ce-b0fc-168d87eac6e1">

**Comment by okdistribute** [comment]
@magicwave can you try 3.0.0? Looks like the tag is 3.0.0 in github releases, despite the heading saying 3.0.6

**Comment by magicwave** [comment]
> @magicwave can you try 3.0.0? Looks like the tag is 3.0.0 in github releases, despite the heading saying 3.0.6
Fails for 3.0.0 also

**Comment by magicwave** [comment]
Turns out it is a github configuration issue on my machine. @kndoshn helped by verfiying `3.0.0 - Next Major` works on his machine. Closing as "not a bug".
