### ISSUE TITLE
Make a maximum version for DittoSwift support

### ISSUE THREAD

**Issue by okdistribute** [getditto/DittoSwiftTools#74]
`.package(url: "https://github.com/getditto/DittoSwiftPackage", from: "4.0.0"),`

Make sure that DittoSwiftTools only supports versions of DittoSwift that we have tested, e.g., 4.0.0-> 5.0.0

**Comment by bplattenburg** [comment]
I dug into this a little, and the current `from:...` syntax does enforce no major version updates with the way SPM expects packages to use SemVer -  `from: "4.0.0"` is the same as `"4.0.0"..<"5.0.0"`.

We can use that longer form syntax if we want to set a specific upper bound besides "next major" but I hope we would not have breaking changes before then.
