### ISSUE TITLE
bug: memory leak in Disk Usage module in 4.6.0

### ISSUE THREAD

**Issue by magicwave** [getditto/DittoSwiftTools#87]
(Unverified) report by a customer noticing memory continuing to grow after viewing Disk Usage in 4.6.0, where this was not observed in v4.4

**Comment by okdistribute** [comment]
Is this an issue with ditto SDK or the tool?

**Comment by magicwave** [comment]
mm... good question. This was reported by NCL and I've passed it along. My assumption was that their use of the SDK did not change, but their observation of DittoSwiftTools behavior changed after an upgrade.

**Comment by bplattenburg** [comment]
This has now been identified as an SDK issue, the fix is tentatively going with the 4.9.0 release in the future.
